<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CompanyWorkforceTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('company_workforce')->truncate();

        \DB::table('company_workforce')->insert([
            0 => [
                'id' => 1,
                'company_id' => 468,
                'user_id' => 469,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => null,
                'status' => 2,
                'created_by' => 468,
                'created_at' => '2021-06-08 09:23:15',
                'updated_by' => null,
                'updated_at' => '2021-06-18 09:23:30',
                'deleted_at' => '2021-06-18 09:23:30'
            ],
            1 => [
                'id' => 2,
                'company_id' => 468,
                'user_id' => 470,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => null,
                'status' => 2,
                'created_by' => 468,
                'created_at' => '2021-06-08 09:23:42',
                'updated_by' => null,
                'updated_at' => '2021-06-17 16:36:21',
                'deleted_at' => '2021-06-17 16:36:21'
            ],
            2 => [
                'id' => 3,
                'company_id' => 468,
                'user_id' => 471,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => null,
                'status' => 2,
                'created_by' => 468,
                'created_at' => '2021-06-08 09:24:04',
                'updated_by' => null,
                'updated_at' => '2021-06-18 09:23:26',
                'deleted_at' => '2021-06-18 09:23:26'
            ],
            3 => [
                'id' => 4,
                'company_id' => 481,
                'user_id' => 479,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '123',
                'status' => 2,
                'created_by' => 481,
                'created_at' => '2021-06-10 14:36:38',
                'updated_by' => null,
                'updated_at' => '2021-06-10 14:36:54',
                'deleted_at' => '2021-06-10 14:36:54'
            ],
            4 => [
                'id' => 5,
                'company_id' => 481,
                'user_id' => 478,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '145',
                'status' => 2,
                'created_by' => 481,
                'created_at' => '2021-06-10 14:37:40',
                'updated_by' => null,
                'updated_at' => '2021-06-10 14:39:06',
                'deleted_at' => '2021-06-10 14:39:06'
            ],
            5 => [
                'id' => 6,
                'company_id' => 481,
                'user_id' => 489,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '236',
                'status' => 2,
                'created_by' => 481,
                'created_at' => '2021-06-10 14:45:21',
                'updated_by' => null,
                'updated_at' => '2021-06-10 14:45:21',
                'deleted_at' => null
            ],
            6 => [
                'id' => 7,
                'company_id' => 481,
                'user_id' => 490,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '999888',
                'status' => 2,
                'created_by' => 481,
                'created_at' => '2021-06-10 14:46:06',
                'updated_by' => 481,
                'updated_at' => '2021-06-10 14:46:29',
                'deleted_at' => null
            ],
            7 => [
                'id' => 8,
                'company_id' => 481,
                'user_id' => 491,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '3322',
                'status' => 2,
                'created_by' => 481,
                'created_at' => '2021-06-10 14:47:04',
                'updated_by' => null,
                'updated_at' => '2021-06-10 14:47:04',
                'deleted_at' => null
            ],
            8 => [
                'id' => 9,
                'company_id' => 493,
                'user_id' => 494,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '444',
                'status' => 2,
                'created_by' => 493,
                'created_at' => '2021-06-10 20:18:21',
                'updated_by' => null,
                'updated_at' => '2021-06-10 20:18:21',
                'deleted_at' => null
            ],
            9 => [
                'id' => 10,
                'company_id' => 467,
                'user_id' => 499,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '123',
                'status' => 2,
                'created_by' => 467,
                'created_at' => '2021-06-17 07:17:07',
                'updated_by' => null,
                'updated_at' => '2021-06-17 07:17:07',
                'deleted_at' => null
            ],
            10 => [
                'id' => 11,
                'company_id' => 467,
                'user_id' => 500,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '124',
                'status' => 2,
                'created_by' => 467,
                'created_at' => '2021-06-17 07:18:02',
                'updated_by' => null,
                'updated_at' => '2021-06-17 07:18:02',
                'deleted_at' => null
            ],
            11 => [
                'id' => 12,
                'company_id' => 481,
                'user_id' => 510,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '555',
                'status' => 2,
                'created_by' => 481,
                'created_at' => '2021-06-17 11:41:34',
                'updated_by' => null,
                'updated_at' => '2021-06-17 11:41:34',
                'deleted_at' => null
            ],
            12 => [
                'id' => 13,
                'company_id' => 468,
                'user_id' => 513,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '123',
                'status' => 2,
                'created_by' => 468,
                'created_at' => '2021-06-18 09:26:34',
                'updated_by' => 468,
                'updated_at' => '2021-06-18 09:27:45',
                'deleted_at' => null
            ],
            13 => [
                'id' => 14,
                'company_id' => 468,
                'user_id' => 514,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => null,
                'status' => 2,
                'created_by' => 468,
                'created_at' => '2021-06-18 09:27:15',
                'updated_by' => null,
                'updated_at' => '2021-06-18 13:14:41',
                'deleted_at' => '2021-06-18 13:14:41'
            ],
            14 => [
                'id' => 15,
                'company_id' => 468,
                'user_id' => 515,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => null,
                'status' => 2,
                'created_by' => 468,
                'created_at' => '2021-06-18 09:27:35',
                'updated_by' => null,
                'updated_at' => '2021-06-18 09:27:35',
                'deleted_at' => null
            ],
            15 => [
                'id' => 16,
                'company_id' => 516,
                'user_id' => 517,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '123333',
                'status' => 2,
                'created_by' => 516,
                'created_at' => '2021-06-18 12:23:50',
                'updated_by' => null,
                'updated_at' => '2021-06-18 12:23:50',
                'deleted_at' => null
            ],
            16 => [
                'id' => 17,
                'company_id' => 516,
                'user_id' => 518,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '1222',
                'status' => 2,
                'created_by' => 516,
                'created_at' => '2021-06-18 12:34:14',
                'updated_by' => null,
                'updated_at' => '2021-06-18 16:39:14',
                'deleted_at' => '2021-06-18 16:39:14'
            ],
            17 => [
                'id' => 18,
                'company_id' => 516,
                'user_id' => 519,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '12345',
                'status' => 2,
                'created_by' => 516,
                'created_at' => '2021-06-18 12:34:59',
                'updated_by' => null,
                'updated_at' => '2021-06-18 16:29:53',
                'deleted_at' => '2021-06-18 16:29:53'
            ],
            18 => [
                'id' => 19,
                'company_id' => 516,
                'user_id' => 520,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '12345',
                'status' => 2,
                'created_by' => 516,
                'created_at' => '2021-06-18 12:35:36',
                'updated_by' => null,
                'updated_at' => '2021-06-18 16:35:51',
                'deleted_at' => '2021-06-18 16:35:51'
            ],
            19 => [
                'id' => 20,
                'company_id' => 516,
                'user_id' => 521,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '1222',
                'status' => 2,
                'created_by' => 516,
                'created_at' => '2021-06-18 16:15:47',
                'updated_by' => null,
                'updated_at' => '2021-06-18 16:15:55',
                'deleted_at' => '2021-06-18 16:15:55'
            ],
            20 => [
                'id' => 21,
                'company_id' => 522,
                'user_id' => 523,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '123',
                'status' => 2,
                'created_by' => 522,
                'created_at' => '2021-06-18 17:58:36',
                'updated_by' => null,
                'updated_at' => '2021-06-18 17:58:36',
                'deleted_at' => null
            ],
            21 => [
                'id' => 22,
                'company_id' => 522,
                'user_id' => 524,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '564',
                'status' => 2,
                'created_by' => 522,
                'created_at' => '2021-06-18 17:59:02',
                'updated_by' => null,
                'updated_at' => '2021-06-18 17:59:02',
                'deleted_at' => null
            ],
            22 => [
                'id' => 23,
                'company_id' => 522,
                'user_id' => 525,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '222',
                'status' => 2,
                'created_by' => 522,
                'created_at' => '2021-06-18 17:59:30',
                'updated_by' => null,
                'updated_at' => '2021-06-18 18:07:22',
                'deleted_at' => '2021-06-18 18:07:22'
            ],
            23 => [
                'id' => 24,
                'company_id' => 528,
                'user_id' => 530,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '222',
                'status' => 2,
                'created_by' => 528,
                'created_at' => '2021-06-20 18:39:07',
                'updated_by' => null,
                'updated_at' => '2021-06-20 18:39:07',
                'deleted_at' => null
            ],
            24 => [
                'id' => 25,
                'company_id' => 528,
                'user_id' => 531,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '12222',
                'status' => 2,
                'created_by' => 528,
                'created_at' => '2021-06-20 18:42:31',
                'updated_by' => null,
                'updated_at' => '2021-06-20 18:42:31',
                'deleted_at' => null
            ],
            25 => [
                'id' => 26,
                'company_id' => 528,
                'user_id' => 532,
                'position_id' => null,
                'department_id' => null,
                'project_id' => null,
                'work_id' => '555',
                'status' => 2,
                'created_by' => 528,
                'created_at' => '2021-06-20 19:49:38',
                'updated_by' => null,
                'updated_at' => '2021-06-20 19:49:38',
                'deleted_at' => null
            ]
        ]);
    }
}
