<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class QuestionOptionsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('question_options')->truncate();
        return;
        \DB::table('question_options')->insert([
            0 => [
                'id' => 1,
                'question_id' => 1,
                'title' => 'a',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 1,
            ],
            1 => [
                'id' => 2,
                'question_id' => 1,
                'title' => 'b',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 2,
            ],
            2 => [
                'id' => 3,
                'question_id' => 1,
                'title' => 'c',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 3,
            ],
            3 => [
                'id' => 4,
                'question_id' => 2,
                'title' => 'a',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 1,
            ],
            4 => [
                'id' => 5,
                'question_id' => 2,
                'title' => 'b',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 2,
            ],
            5 => [
                'id' => 6,
                'question_id' => 2,
                'title' => 'c',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 3,
            ],
            6 => [
                'id' => 7,
                'question_id' => 2,
                'title' => 'd',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 4,
            ],
            7 => [
                'id' => 8,
                'question_id' => 2,
                'title' => 'e',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 5,
            ],
            8 => [
                'id' => 9,
                'question_id' => 4,
                'title' => 'a',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 1,
            ],
            9 => [
                'id' => 10,
                'question_id' => 4,
                'title' => 'b',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 2,
            ],
            10 => [
                'id' => 11,
                'question_id' => 4,
                'title' => 'c',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 3,
            ],
            11 => [
                'id' => 12,
                'question_id' => 5,
                'title' => 'a',
                'image_id' => null,
                'd_pref' => 'image',
                'is_correct' => 1,
                'sort_order' => 1,
            ],
            12 => [
                'id' => 13,
                'question_id' => 5,
                'title' => 'b',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 2,
            ],
            13 => [
                'id' => 14,
                'question_id' => 5,
                'title' => 'c',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 3,
            ],
            14 => [
                'id' => 15,
                'question_id' => 5,
                'title' => 'd',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 4,
            ],
            15 => [
                'id' => 16,
                'question_id' => 5,
                'title' => 'e',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 5,
            ],
            16 => [
                'id' => 17,
                'question_id' => 8,
                'title' => 'a',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 1,
            ],
            17 => [
                'id' => 18,
                'question_id' => 8,
                'title' => 'b',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 2,
            ],
            18 => [
                'id' => 19,
                'question_id' => 8,
                'title' => 'c',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 3,
            ],
            19 => [
                'id' => 20,
                'question_id' => 9,
                'title' => 'a',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 1,
            ],
            20 => [
                'id' => 21,
                'question_id' => 9,
                'title' => 'b',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 2,
            ],
            21 => [
                'id' => 22,
                'question_id' => 9,
                'title' => 'c',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 3,
            ],
            22 => [
                'id' => 23,
                'question_id' => 10,
                'title' => 'a',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 1,
            ],
            23 => [
                'id' => 24,
                'question_id' => 10,
                'title' => 'b',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 1,
                'sort_order' => 2,
            ],
            24 => [
                'id' => 25,
                'question_id' => 10,
                'title' => 'c',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 3,
            ],
            25 => [
                'id' => 26,
                'question_id' => 10,
                'title' => 'd',
                'image_id' => null,
                'd_pref' => 'text',
                'is_correct' => 0,
                'sort_order' => 4,
            ],
        ]);
    }
}
