<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RequiredCourseWorkforcesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('required_course_workforces')->truncate();

        \DB::table('required_course_workforces')->insert([
            0 => [
                'id' => 5,
                'course_id' => 4,
                'department_id' => 6,
                'course_purchase_id' => null,
                'user_id' => 470,
                'certificate' => '60bf3f20cb929.jpg',
                'issue_date' => '2019-07-08',
                'expiry_date' => '2020-10-07',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-08 11:57:52',
                'updated_by' => 468,
                'updated_at' => '2021-06-08 11:58:34',
                'deleted_at' => null
            ],
            1 => [
                'id' => 6,
                'course_id' => 9,
                'department_id' => 8,
                'course_purchase_id' => null,
                'user_id' => 491,
                'certificate' => '60c24ea1d01b7.jpg',
                'issue_date' => '2021-06-08',
                'expiry_date' => '2007-05-06',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '2021-06-11',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-10 19:37:58',
                'updated_by' => 481,
                'updated_at' => '2021-06-10 19:39:51',
                'deleted_at' => null
            ],
            2 => [
                'id' => 7,
                'course_id' => 9,
                'department_id' => 8,
                'course_purchase_id' => null,
                'user_id' => 490,
                'certificate' => '60c24ea1d01b7.jpg',
                'issue_date' => '2021-06-08',
                'expiry_date' => '2021-07-07',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-10 19:40:29',
                'updated_by' => 481,
                'updated_at' => '2021-06-10 19:40:49',
                'deleted_at' => null
            ],
            3 => [
                'id' => 8,
                'course_id' => 8,
                'department_id' => 7,
                'course_purchase_id' => null,
                'user_id' => 489,
                'certificate' => '60c24ea1d01b7.jpg',
                'issue_date' => '2021-06-08',
                'expiry_date' => '1905-05-10',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-10 19:42:39',
                'updated_by' => 481,
                'updated_at' => '2021-06-10 19:47:01',
                'deleted_at' => null
            ],
            4 => [
                'id' => 10,
                'course_id' => 8,
                'department_id' => 7,
                'course_purchase_id' => null,
                'user_id' => 510,
                'certificate' => '60cb191896d79.jpg',
                'issue_date' => '2021-06-17',
                'expiry_date' => '2021-07-23',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '2021-06-18',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-17 11:42:48',
                'updated_by' => null,
                'updated_at' => '2021-06-17 11:42:48',
                'deleted_at' => null
            ],
            5 => [
                'id' => 11,
                'course_id' => 8,
                'department_id' => 7,
                'course_purchase_id' => null,
                'user_id' => 510,
                'certificate' => '60cb1924b2f49.jpg',
                'issue_date' => '2021-06-17',
                'expiry_date' => '2021-07-23',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '2021-06-18',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-17 11:43:00',
                'updated_by' => null,
                'updated_at' => '2021-06-17 11:43:00',
                'deleted_at' => null
            ],
            6 => [
                'id' => 12,
                'course_id' => 8,
                'department_id' => 7,
                'course_purchase_id' => null,
                'user_id' => 510,
                'certificate' => '60cb1925350d9.jpg',
                'issue_date' => '2021-06-17',
                'expiry_date' => '2021-07-23',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '2021-06-18',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-17 11:43:01',
                'updated_by' => null,
                'updated_at' => '2021-06-17 11:43:01',
                'deleted_at' => null
            ],
            7 => [
                'id' => 13,
                'course_id' => 16,
                'department_id' => 14,
                'course_purchase_id' => null,
                'user_id' => 514,
                'certificate' => '60cc4dc453ef6.png',
                'issue_date' => '2021-06-17',
                'expiry_date' => '2022-06-16',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-18 09:39:48',
                'updated_by' => null,
                'updated_at' => '2021-06-18 09:39:48',
                'deleted_at' => null
            ],
            8 => [
                'id' => 14,
                'course_id' => 17,
                'department_id' => 14,
                'course_purchase_id' => null,
                'user_id' => 514,
                'certificate' => '60cc4ed13a0dd.png',
                'issue_date' => '2020-10-22',
                'expiry_date' => '2021-07-21',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-18 09:41:18',
                'updated_by' => 468,
                'updated_at' => '2021-06-18 09:44:17',
                'deleted_at' => null
            ],
            9 => [
                'id' => 15,
                'course_id' => 15,
                'department_id' => 13,
                'course_purchase_id' => null,
                'user_id' => 513,
                'certificate' => '60cc4f728efe1.png',
                'issue_date' => '2020-11-10',
                'expiry_date' => '2021-05-09',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-18 09:46:58',
                'updated_by' => null,
                'updated_at' => '2021-06-18 09:46:58',
                'deleted_at' => null
            ],
            10 => [
                'id' => 17,
                'course_id' => 18,
                'department_id' => null,
                'course_purchase_id' => null,
                'user_id' => 517,
                'certificate' => '60cc780866612.jpg',
                'issue_date' => '2021-02-03',
                'expiry_date' => '2021-06-02',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-18 12:40:08',
                'updated_by' => null,
                'updated_at' => '2021-06-18 16:11:29',
                'deleted_at' => null
            ],
            11 => [
                'id' => 23,
                'course_id' => 27,
                'department_id' => 20,
                'course_purchase_id' => null,
                'user_id' => 523,
                'certificate' => '60ccc3a27e24d.png',
                'issue_date' => '2021-06-16',
                'expiry_date' => '2021-10-15',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-18 18:02:42',
                'updated_by' => null,
                'updated_at' => '2021-06-18 18:02:42',
                'deleted_at' => null
            ],
            12 => [
                'id' => 27,
                'course_id' => 29,
                'department_id' => 23,
                'course_purchase_id' => null,
                'user_id' => 531,
                'certificate' => '60cf70d268e55.jpg',
                'issue_date' => '2021-06-20',
                'expiry_date' => '2021-09-19',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '1970-01-01',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-20 18:45:13',
                'updated_by' => 528,
                'updated_at' => '2021-06-20 18:46:10',
                'deleted_at' => null
            ],
            13 => [
                'id' => 28,
                'course_id' => 29,
                'department_id' => 23,
                'course_purchase_id' => null,
                'user_id' => 532,
                'certificate' => '60cf7fdaa7c04.jpg',
                'issue_date' => '2021-06-13',
                'expiry_date' => '2021-06-14',
                'certificate_status' => 1,
                'upload_status' => 1,
                'status' => 1,
                'start_date' => '2021-06-20',
                'end_date' => null,
                'created_by' => null,
                'created_at' => '2021-06-20 19:50:18',
                'updated_by' => null,
                'updated_at' => '2021-06-20 19:50:18',
                'deleted_at' => null
            ]
        ]);
    }
}
