<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Seeder;

class TagsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*        $tags = [
            '3D Animation',
            '3D Printing',
            'Accessible',
            'Accounting',
            'Accounting and Finance',
            'Accounting Information Systems',
            'Accounting Principles',
            'Actionable',
            'Active learning',
            'Adaptability',
            'Adaptive',
            'Addiction Counseling',
            'Adidas',
            'Adobe Creative Suite',
            'Adult Friend Finder',
            'Advertising',
            'Advertising and Public Relations',
            'Advertising Management',
            'Aerospace Engineering',
            'African American Studies',
            'African-American History',
            'Agile',
            'Agile Development',
            'Agile Methodology',
            'Aging and Gerontology',
            'Agricultural Economics',
            'Agricultural Science',
            'Agronomy',
            'Air Traffic Control',
            'Airbnb',
            'Algorithmic Trading',
            'Alibaba',
            'Amazon',
            'Amazon Music',
            'American Government and Politics',
            'American Politics',
            'American Sign Language',
            'Analytical',
            'Analytical skills',
            'Analytics',
            'Anatomy and Physiology',
            'Ancient History',
            'Android Development',
            'Animal Behavior',
            'Animal Science',
            'Animation',
            'Animation and Illustration',
            'Anthropology',
            'Apple Music',
            'Applied Linguistics',
            'Applied Mathematics',
            'Applied Physics',
            'Arabic Language',
            'Archaeology',
            'Architectural Design',
            'Architecture',
            'Art History',
            'Artificial Intelligence',
            'Artificial Life',
            'Artificial Neural Networks',
            'Ashley Madison',
            'Asian History',
            'Asian Studies',
            'ASOS',
            'Asset Management',
            'Astronomy',
            'Astrophysics',
            'Audio Engineering',
            'Auditing and Assurance',
            'Augmented Reality',
            'Autism Spectrum Disorders',
            'AutoCAD',
            'Automotive Engineering',
            'Aviation',
            'Aviation Management',
            'Bandcamp',
            'Banking and Finance',
            'Banking and Financial Services',
            'Bebo',
            'Behance',
            'Behavior Analysis',
            'Behavioral Economics',
            'Behavioral Psychology',
            'Biblical Studies',
            'Big Data Analytics',
            'Biochemistry',
            'Biodiversity',
            'Bioinformatics',
            'Biology',
            'Biomechanics',
            'Biomedical Engineering',
            'Biostatistics',
            'Biotechnology',
            'Bite-sized learning',
            'Blended learning',
            'Blockchain Technology',
            'Brand Management',
            'Bumble',
            'Business Administration',
            'Business Analysis',
            'Business Analytics',
            'Business Communication',
            'Business Ethics',
            'Business Intelligence',
            'Business Law',
            'Business Strategy',
            'Business Writing',
            'Cancer Biology',
            'Cancer Research',
            'Cardiovascular Disease',
            'Cardiovascular Health',
            'Career development',
            'Case-based learning',
            'CDBaby',
            'Cell Biology',
            'Change management',
            'Chemical Engineering',
            'Chemistry',
            'Child Development',
            'Child Psychology',
            'Chinese Language',
            'Cinematography',
            'Civil Engineering',
            'Civil Litigation',
            'Climate Change',
            'Climate Science',
            'Clinical Psychology',
            'Cloud Computing',
            'Cloud Security',
            'Coffee Meets Bagel',
            'Cognitive Psychology',
            'Cognitive Science',
            'Collaborative',
            'Collaborative Leadership',
            'Collaborative learning',
            'Collaborative problem-solving',
            'Columbia',
            'Commercial Law',
            'Communication',
            'Communication Design',
            'Communication Disorders',
            'Communication skills',
            'Communication Studies',
            'Community Development',
            'Community Health',
            'Comparative Literature',
            'Comprehensive',
            'Computational Linguistics',
            'Computer Architecture',
            'Computer Networking',
            'Computer Networks',
            'Computer Programming',
            'Computer Science',
            'Conflict Resolution',
            'Conservation Biology',
            'Construction Engineering',
            'Construction Management',
            'Consumer Behavior',
            'Consumer Psychology',
            'Continuous improvement',
            'Corporate Finance',
            'Corporate Governance',
            'Corporate Social Responsibility',
            'Cosmetic Science',
            'Cost Accounting',
            'Counseling Psychology',
            'Creative',
            'Creative Writing',
            'Creativity',
            'Criminal Justice',
            'Criminal Law',
            'Criminology',
            'Crisis Management',
            'Critical thinking',
            'Cross-Cultural Communication',
            'Cross-platform',
            'Cryptocurrency',
            'Cryptography',
            'Culinary Arts',
            'Cultural Anthropology',
            'Cultural Studies',
            'Curriculum Design',
            'Curriculum Development',
            'Customizable',
            'Cutting-edge',
            'Cyber Defense',
            'Cyber Forensics',
            'Cyber Law',
            'Cybersecurity',
            'Dance',
            'Data Analysis',
            'Data Analytics',
            'Data Mining',
            'Data Science',
            'Data Warehousing',
            'Database Management',
            'Data-driven',
            'Decision Making',
            'Decision Science',
            'Decision Sciences',
            'Decision-making',
            'Deep Learning',
            'Deezer',
            'Dental Hygiene',
            'Dental Science',
            'Dental Surgery',
            'Dentistry',
            'Dermatology',
            'Design',
            'Design thinking',
            'Developmental Psychology',
            'DevOps',
            'Digital Art',
            'Digital Communication',
            'Digital Forensics',
            'Digital Marketing',
            'Digital Media',
            'Digital Media Production',
            'Digital Photography',
            'Digital transformation',
            'Directing',
            'Disability Studies',
            'Disaster Management',
            'Disaster Recovery',
            'Discord',
            'Distance learning',
            'Distributed Systems',
            'Diversity and Inclusion',
            'Documentary Filmmaking',
            'DoorDash',
            'Dribbble',
            'Drug Development',
            'Drug Discovery',
            'Dynamic',
            'Early Childhood Education',
            'Earth Science',
            'East Asian Studies',
            'Easy-to-use',
            'eBay',
            'Ecology and Evolution',
            'E-commerce',
            'Econometrics',
            'Economic Development',
            'Economic History',
            'Economics',
            'Ecosystem Science',
            'Editing',
            'Education',
            'Education Policy',
            'Educational',
            'Educational Leadership',
            'Educational Psychology',
            'Educational Technology',
            'Efficient',
            'eHarmony',
            'E-learning',
            'Electric Power Systems',
            'Electrical Engineering',
            'Electronic Commerce',
            'Electronic Music Production',
            'Electronics',
            'Elementary Education',
            'Elite Singles',
            'Emergency Management',
            'Emerging technologies',
            'Emotional intelligence',
            'Empowering',
            'Energy Engineering',
            'Energy Management',
            'Energy Policy',
            'Engaging',
            'Engineering',
            'Engineering Ethics',
            'Engineering Geology',
            'Engineering Management',
            'English Language',
            'English Language and Literature',
            'Engrossing',
            'Enlightening',
            'Enterprise Architecture',
            'Entertaining',
            'Entrepreneurial Finance',
            'Entrepreneurship',
            'Environmental Engineering',
            'Environmental Health',
            'Environmental Law',
            'Environmental Planning',
            'Environmental Policy',
            'Environmental Policy and Management',
            'Environmental Science',
            'Epidemiology',
            'Equity Research',
            'Ethical Hacking',
            'Ethics',
            'Ethics and Moral Philosophy',
            'Etsy',
            'European History',
            'European Studies',
            'Event Management',
            'Event Planning',
            'Event Planning and Management',
            'Eventbrite',
            'Evidence-based',
            'Evolutionary Biology',
            'Evolutionary Psychology',
            'Exciting',
            'Exercise Physiology',
            'Exercise Science',
            'Expedia',
            'Experiential',
            'Experiential learning',
            'Facebook',
            'Family Law',
            'Fashion Design',
            'Fashion Merchandising',
            'Federal Taxation',
            'Feminist Studies',
            'FetLife',
            'Film Production',
            'Film Studies',
            'Finance',
            'Financial Accounting',
            'Financial Analysis',
            'Financial Management',
            'Financial Markets',
            'Financial Modeling',
            'Fine Arts',
            'Fire Science',
            'Fisheries Science',
            'Flickr',
            'Food Chemistry',
            'Food Safety',
            'Food Science',
            'Food Science and Nutrition',
            'Foreign Policy',
            'Forensic Accounting',
            'Forensic Psychology',
            'Forensic Science',
            'Forensic Toxicology',
            'Forever 21',
            'French Language',
            'Friendster',
            'Fun',
            'Game Design',
            'Game Design and Development',
            'Game Development',
            'Game Theory',
            'Game-based learning',
            'Gamified learning',
            'Gender and Sexuality Studies',
            'Gender Studies',
            'General Biology',
            'General Chemistry',
            'General Physics',
            'Genetic Engineering',
            'Genetics',
            'Genetics and Genomics',
            'Geographical Information Systems',
            'Geology',
            'Geology and Earth Science',
            'Geophysics',
            'Geotechnical Engineering',
            'Geriatric Medicine',
            'German Language',
            'Global Health',
            'Global Marketing',
            'Globalization',
            'Globalization Studies',
            'Goal setting',
            'Goal-oriented',
            'Google Play Music',
            'Google+',
            'Government Accounting',
            'Graphic Design',
            'Greek Language',
            'Green Energy',
            'Grindr',
            'Growth mindset',
            'Grubhub',
            'H&M',
            'Health Communication',
            'Health Informatics',
            'Health Policy',
            'Health Policy and Management',
            'Health Promotion',
            'Health Psychology',
            'Health Sciences',
            'Healthcare Administration',
            'Healthcare Management',
            'Hi5',
            'High Performance Computing',
            'Hinduism',
            'Hinge',
            'History',
            'History of Art',
            'History of Science and Technology',
            'Hospitality and Tourism Management',
            'Hospitality Management',
            'Hospitality Marketing',
            'Human Anatomy',
            'Human Anatomy and Physiology',
            'Human Resource Management',
            'Human Resources',
            'Human Rights',
            'Human-Computer Interaction',
            'Humanities and Social Sciences',
            'Hydrology',
            'iHeartRadio',
            'In-depth',
            'Industrial Design',
            'Industrial Engineering',
            'Information Systems Security',
            'Information Technology',
            'Informative',
            'Infrastructure Management',
            'Innovation',
            'Innovation and Entrepreneurship',
            'Innovation management',
            'Innovative',
            'Insect Ecology',
            'Insight-driven',
            'Insightful',
            'Inspiring',
            'Instacart',
            'Instagram',
            'Instructional Design',
            'Insurance and Risk Management',
            'Insurance Law',
            'Intellectual Property',
            'Intellectual Property Law',
            'Intense',
            'Interactive',
            'Interior Design',
            'International Business',
            'International Development',
            'International Relations',
            'Internet Marketing',
            'Internet of Things',
            'Internet of Things (IoT)',
            'Interpersonal skills',
            'Intuitive',
            'Investment Banking',
            'Investment Management',
            'Islamic Finance',
            'Islamic Studies',
            'Italian Language',
            'iTunes',
            'Japanese Language',
            'JD.com',
            'Journalism',
            'Journalism and Mass Communication',
            'Just-in-time learning',
            'Knowledge Management',
            'Korean Language',
            'Labor Economics',
            'Landscape Architecture',
            'Last.fm',
            'Latin American History',
            'Law',
            'Law and Legal Studies',
            'Law and Society',
            'Leadership',
            'Leadership and Management',
            'Leadership Development',
            'Leadership skills',
            'Learning and Development',
            'Legal Studies',
            'Legal Writing',
            'Linguistics',
            'LinkedIn',
            'Literary Criticism',
            'Literary Studies',
            'Literary Theory',
            'Logistics',
            'Logistics and Supply Chain Management',
            'Lululemon',
            'Lyft',
            'Machine Learning',
            'Management',
            'Management Accounting',
            'Management Information Systems',
            'Management skills',
            'Manufacturing Engineering',
            'Marine Biology',
            'Market Research',
            'Marketing',
            'Marketing Analytics',
            'Marketing Research',
            'Marketing Research and Analytics',
            'Marketing Strategy',
            'Mass Communication',
            'Match',
            'Materials Science',
            'Materials Science and Engineering',
            'Mathematical Biology',
            'Mathematics',
            'Mathematics and Statistics',
            'Measurable',
            'Mechanical Design',
            'Mechanical Engineering',
            'Media Production',
            'Media Studies',
            'Medical Billing and Coding',
            'Medical Ethics',
            'Medical Imaging',
            'Medical Laboratory Science',
            'Medical Physics',
            'Medical Sociology',
            'Medical Terminology',
            'Medicine',
            'Medieval Studies',
            'Meetup',
            'Mental health',
            'Mental Health Counseling',
            'Meteorology',
            'Methodical',
            'Microbiology',
            'Microeconomics',
            'Microlearning',
            'Middle Eastern Studies',
            'Military Science',
            'Mindfulness',
            'Mining Engineering',
            'Mixcloud',
            'Mobile App Development',
            'Mobile Application Development',
            'Mobile-friendly',
            'Modern Art',
            'Modern European History',
            'Modern Languages',
            'Molecular Biology',
            'Motivational',
            'Multidimensional',
            'Multifaceted',
            'Music Composition',
            'Music Education',
            'Music History',
            'Music Production',
            'Music Production and Engineering',
            'Music Theory',
            'MySpace',
            'Nanotechnology',
            'Napster',
            'Natural Language Processing',
            'Natural Resource Management',
            'Net-a-Porter',
            'Network Security',
            'Neurobiology',
            'Neuroscience',
            'Nike',
            'Nonprofit Management',
            'Nuclear Engineering',
            'Numerical Analysis',
            'Nursing',
            'Nursing Education',
            'Nutrition',
            'Nutrition and Dietetics',
            'Nutrition Science',
            'Occupational Health and Safety',
            'Occupational Therapy',
            'Oceanography',
            'OkCupid',
            'On-demand learning',
            'Online learning',
            'Online Reputation Management',
            'Operations Management',
            'Organizational Behavior',
            'Organizational Communication',
            'Organizational Development',
            'Organizational Psychology',
            'Orkut',
            'Orthopedic Surgery',
            'Outcome-focused',
            'Packaging Design',
            'Paleontology',
            'Pandora',
            'Paralegal Studies',
            'Patagonia',
            'Patent Law',
            'Pathology',
            'Pedagogy and Teaching Methods',
            'Pediatric Nursing',
            'Peer-to-peer learning',
            'Performance Management',
            'Performance-based',
            'Performing Arts',
            'Periscope',
            'Personal Finance',
            'Personalized',
            'Petroleum Engineering',
            'Pharmaceutical Science',
            'Pharmacology',
            'Philosophy',
            'Philosophy of Science',
            'Photography',
            'Photography and Video',
            'Physical Chemistry',
            'Physical Education',
            'Physical health',
            'Physical Therapy',
            'Physician Assistant Studies',
            'Physics',
            'Physiology',
            'Pinterest',
            'Plant Biology',
            'Plant Science',
            'Plenty of Fish',
            'Political Philosophy',
            'Political Science',
            'Portfolio Management',
            'Portuguese Language',
            'Positive attitude',
            'Postmates',
            'Poverty and Development',
            'Power Electronics',
            'Practical',
            'Predictive Analytics',
            'Problem-based learning',
            'Product Design',
            'Professional skills',
            'Professional Writing',
            'Progress-oriented',
            'Project management',
            'Project Planning',
            'Project-based learning',
            'Psychiatric Mental Health',
            'Psychology',
            'Psychology of Religion',
            'Public Administration',
            'Public Health',
            'Public Policy',
            'Public Relations',
            'Public Speaking',
            'Puma',
            'Quality Assurance',
            'Quality Management',
            'Quantitative Finance',
            'Rakuten',
            'Real Estate',
            'Real Estate Finance',
            'Real Estate Law',
            'Reddit',
            'Reflective learning',
            'Rehabilitation Counseling',
            'Relevant',
            'Religion',
            'Renewable Energy',
            'Renewable Energy Policy',
            'Renewable Energy Technologies',
            'Research Methods',
            'Resilience',
            'Resourceful',
            'Responsive',
            'Results-driven',
            'Retail Management',
            'ReverbNation',
            'Risk Assessment',
            'Risk Management',
            'Robotics',
            'Robotics and Automation',
            'Robotics Engineering',
            'Robotics Technology',
            'Role-playing',
            'Sales',
            'Sales and Business Development',
            'Sales and Marketing',
            'Sales Management',
            'Scalable',
            'Scandinavian Studies',
            'Scenario-based learning',
            'Science Communication',
            'Science Fiction Studies',
            'Scrum',
            'Sculpture and Ceramics',
            'Search Engine Optimization',
            'Security Management',
            'Seeking Arrangement',
            'Self-awareness',
            'Self-directed learning',
            'Self-motivation',
            'Self-paced learning',
            'Sephora',
            'Service Management',
            'Shazam',
            'Shopify',
            'Simulation-based learning',
            'SiriusXM',
            'Skype',
            'Snapchat',
            'Social Capital',
            'Social Change',
            'Social Cognition',
            'Social Comparison',
            'Social Comparison Theory',
            'Social Constructionism',
            'Social Contract Theory',
            'Social Darwinism',
            'Social Development',
            'Social Engineering',
            'Social Entrepreneurship',
            'Social Exchange Theory',
            'Social History',
            'Social Identity',
            'Social Identity Theory',
            'Social Impact',
            'Social Inequality',
            'Social Influence',
            'Social Innovation',
            'Social Interaction',
            'Social Issues',
            'Social Justice',
            'Social learning',
            'Social Learning Theory',
            'Social Media',
            'Social Media Marketing',
            'Social Movements',
            'Social Networking',
            'Social Norms',
            'Social Perception',
            'Social Policy',
            'Social Psychology',
            'Social Responsibility',
            'Social Responsibility Accountability',
            'Social Responsibility Accounting',
            'Social Responsibility Advocacy',
            'Social Responsibility Auditing',
            'Social Responsibility Benchmarking',
            'Social Responsibility Coaching',
            'Social Responsibility Collaboration',
            'Social Responsibility Communication',
            'Social Responsibility Community',
            'Social Responsibility Consulting',
            'Social Responsibility Consumer',
            'Social Responsibility Culture',
            'Social Responsibility Customer Service',
            'Social Responsibility Development',
            'Social Responsibility Diversity',
            'Social Responsibility Economic Sustainability',
            'Social Responsibility Education',
            'Social Responsibility Effectiveness',
            'Social Responsibility Efficiency',
            'Social Responsibility Employee',
            'Social Responsibility Empowerment',
            'Social Responsibility Environment',
            'Social Responsibility Environmental Sustainability',
            'Social Responsibility Equality',
            'Social Responsibility Ethics',
            'Social Responsibility Fairness',
            'Social Responsibility Framework',
            'Social Responsibility Global',
            'Social Responsibility Growth',
            'Social Responsibility Health',
            'Social Responsibility Human Rights',
            'Social Responsibility Inclusion',
            'Social Responsibility Index',
            'Social Responsibility Initiatives',
            'Social Responsibility Innovation',
            'Social Responsibility Investment',
            'Social Responsibility Investor',
            'Social Responsibility Justice',
            'Social Responsibility Law',
            'Social Responsibility Leadership',
            'Social Responsibility Management',
            'Social Responsibility Marketing',
            'Social Responsibility Metrics',
            'Social Responsibility Nation',
            'Social Responsibility Partner',
            'Social Responsibility Partnership',
            'Social Responsibility People',
            'Social Responsibility Performance',
            'Social Responsibility Philanthropy',
            'Social Responsibility Planet',
            'Social Responsibility Policy',
            'Social Responsibility Productivity',
            'Social Responsibility Programs',
            'Social Responsibility Prosperity',
            'Social Responsibility Quality',
            'Social Responsibility Regulator',
            'Social Responsibility Reporting',
            'Social Responsibility Reputation',
            'Social Responsibility Respect',
            'Social Responsibility Safety',
            'Social Responsibility Shareholder',
            'Social Responsibility Social Sustainability',
            'Social Responsibility Society',
            'Social Responsibility Stakeholder',
            'Social Responsibility Standards',
            'Social Responsibility Success',
            'Social Responsibility Supplier',
            'Social Responsibility Sustainability',
            'Social Responsibility Sustainability Development',
            'Social Responsibility Theory',
            'Social Responsibility Training',
            'Social Responsibility Transparency',
            'Social Responsibility Triple Bottom Line',
            'Social Responsibility Trust',
            'Social Responsibility Value',
            'Social Services',
            'Social Stratification',
            'Social Studies',
            'Social Support',
            'Social Theory',
            'Social Welfare',
            'Social Work',
            'Socialization',
            'Socialization Theory',
            'Sociology',
            'Sociology of Health',
            'Soft skills',
            'Software Development',
            'Software Engineering',
            'Software Testing',
            'Solar Energy',
            'Sophisticated',
            'SoundCloud',
            'Spanish Language',
            'Special Education',
            'Speech and Language Pathology',
            'Speech Therapy',
            'Speech-Language Pathology',
            'Sports Coaching and Management',
            'Sports Management',
            'Sports Medicine',
            'Sports Nutrition',
            'Sports Psychology',
            'Spotify',
            'Statistical Analysis',
            'Statistical Inference',
            'Statistical Learning',
            'Statistics',
            'Strategic Management',
            'Strategic Planning',
            'Streamlined',
            'Stress management',
            'Structural Engineering',
            'Structural Mechanics',
            'Structured',
            'Supply Chain Management',
            'Sustainability',
            'Sustainability Studies',
            'Sustainable Agriculture',
            'Sustainable Design',
            'Sustainable Development',
            'Systems Analysis',
            'Tagged',
            'Taobao',
            'Tax Planning',
            'Taxation',
            'Taxation Law',
            'Teacher Education',
            'Teaching',
            'Teaching English as a Foreign Language',
            'Teaching English as a Second Language',
            'Teamwork',
            'Technical Communication',
            'Technical skills',
            'Technical Writing',
            'Technology and Innovation Management',
            'Technology Management',
            'Telecommunications',
            'Telecommunications Engineering',
            'Telecommunications Management',
            'Telegram',
            'Terrorism and Counterterrorism',
            'Terrorism Studies',
            'Text Analytics',
            'Textile Design',
            'The North Face',
            'Theater Studies',
            'Theatre Arts',
            'Theology',
            'Theology and Religious Studies',
            'Thought-provoking',
            'Tidal',
            'TikTok',
            'Time management',
            'Tinder',
            'Tourism and Hospitality',
            'Tourism Management',
            'Toxicology',
            'Trackable',
            'Transformative',
            'Translation and Interpretation',
            'Transportation Engineering',
            'Transportation Planning',
            'Travel Writing',
            'TripAdvisor',
            'Tumblr',
            'TuneCore',
            'Twitter',
            'Uber',
            'Ulta',
            'Under Armour',
            'Urban Planning',
            'Urban Planning and Design',
            'User Experience',
            'User Experience Design',
            'User Interface Design',
            'User-friendly',
            'Venture Capital',
            'Versatile',
            'Veterinary Medicine',
            'Viber',
            'Video Editing',
            'Video Production',
            'Vimeo',
            'Virtual learning',
            'Virtual Reality',
            'Visual Arts',
            'Water Resources Engineering',
            'Web Analytics',
            'Web Design',
            'Web Design and Development',
            'Web Development',
            'Website Development',
            'WeChat',
            'Well-being',
            'Well-organized',
            'WhatsApp',
            'Wildlife Biology',
            'Wildlife Conservation',
            'Wildlife Management',
            'Wireless Networking',
            'Women\'s Health',
            'Women\'s Studies',
            'World History',
            'World Literature',
            'Writing and Editing',
            'Writing and Rhetoric',
            'Writing Skills',
            'Xanga',
            'Yelp',
            'Youth Development',
            'YouTube',
            'Zalando',
            'Zara',
            'Zoology',
            'Zoom',
            'Zoosk',
        ];*/

        //        foreach ($tags as $tag) {
        //            Tag::updateOrCreate(['name' => $tag]);
        //        }

        //        $tag1 = Tag::create(['name' => 'tag 1']);
        //        $tag2 = Tag::create(['name' => 'tag 2']);
    }
}
