<?php
//define('USER_KEY_ALPHA','UVWXYZABCDEFNOPQRSTGHIJKLM');
//define('USER_KEY_NUM','963258741');

return [
    'USER_KEY_ALPHA' => 'UVWXYZABCDEFNOPQRSTGHIJKLM',
    'USER_KEY_NUM'   => '963258741'
];
