<?php

return [
    "gender"=>[
        "male",
        "female",
    ],
    "Levels_of_education"=>[
        "Early childhood education ",
        "Primary education",
        "Lower secondary education",
        "Upper secondary education",
        "Post-secondary non-tertiary education",
        "Short-cycle tertiary education",
        "Bachelor’s or equivalent level",
        "Master’s or equivalent level",
        "Doctoral or equivalent level",

    ],
    "Employment_status"=>[
        "Employee ",
        "Unemployed ",
        "Self-employed",
        "Student ",
    ],
    "EDUCATIONAL_MAJORS"=>[
        "AGRICULTURE"=>[
            "Agricultural Business",
            "Agricultural Economics",
            "Agricultural Mechanics",
            "Agronomy",
            "Animal Sciences",
            "Farm and Ranch Management",
            "Fish, Game, Wildlife Management",
            "Forestry",
            "Horticulture",
            "Natural Resources Management",
            "Other Agriculture Majors",
        ],
        "ARCHITECTURE"=>[
            "Architectural Drafting",
            "City & Regional Planning",
            "Environmental Design",
            "Interior Design",
            "Landscape Architecture",
            "Other Architecture Majors",
        ],
        "BIOLOGICAL SCIENCES"=>[
            "Biochemistry/Biophysics",
            "Biology",
            "Botany",
            "Ecology",
            "Microbiology",
            "Zoology",
            "Other Biological Sciences",
        ],
        "BUSINESS"=>[
            "Business Management",
            "Accounting",
            "Banking & Finance",
            "Contract Management",
            "Hotel/Restaurant Management",
            "Human Res. Development/Training",
            "Insurance & Risk Management",
            "Labor/Industrial Relations",
            "Management Information Systems",
            "Organizational Behavior",
            "Personnel Management",
            "Real Estate Management",
            "Trade & Industrial Management",
            "Transportation",
        ],
        "OFFICE MANAGEMENT"=>[
            "Bookkeeping",
            "Business/Computer Operations",
            "Court Reporting",
            "Secretarial Studies",
            "Word Processing",
            "Other Office Management",
        ],
        "MARKETING & PURCHASING"=>[
            "Fashion Merchandising",
            "Retailing & Sales",
            "Travel Services & Tourism",
            "Other Marketing & Purchasing",
        ],
        "COMMUNICATIONS"=>[
            "Advertising",
            "Commercial Art",
            "Journalism",
            "Public Relations",
            "Radio/TV Broadcasting",
            "Other Communications",
        ],
        "COMMUNITY SERVICES"=>[
            "Corrections",
            "Cosmetology/Barbering",
            "Criminal Justice",
            "Fire Protection",
            "Mortuary Science",
            "Law Enforcement",
            "Library Science",
            "Military Science",
            "Parks & Recreation",
            "Public Administration",
            "Social Work",
            "Other Community Services",
        ],
        "COMPUTER & INFORMATION SCIENCES"=>[
            "Computer Programming",
            "Computer Science",
            "Data Processing",
            "Information Systems",
            "Other Computer & Information Sciences",
        ],
        "GENERAL STUDIES"=>[
            "Area & Ethnic Studies",
            "Multi/Interdisciplinary Studies",
            "Liberal Arts/Other General Studies",
        ],
        "EDUCATION"=>[
            "Adult & Continuing Education",
            "Education Administration",
            "Elementary Education",
            "Secondary Education",
            "Student Counseling",
            "Physical Education",
            "Special Education",
            "Other Education Majors",
        ],
        "ENGINEERING"=>[
            "Aerospace Engineering",
            "Bioengin. & Biomed. Engineering",
            "Chemical Engineering",
            "Civil Engineering",
            "Electrical & Electronic Engineering",
            "Environmental Health Engineering",
            "Industrial Engineering",
            "Materials Engineering",
            "Mechanical Engineering",
            "Mining/Mineral Engineering",
            "Nuclear Engineering",
            "Ocean Engineering",
            "Petroleum Engineering",
            "Other Engineering Majors",
        ],
        "FINE & APPLIED ARTS"=>[
            "Applied Design/Crafts",
            "Art",
            "Art History",
            "Cinematography",
            "Dance",
            "Dramatic Arts",
            "Graphic Design",
            "Music",
            "Photography",
            "Other Fine & Applied Arts",
        ],
        "FOREIGN LANGUAGES"=>[
            "FOREIGN LANGUAGES"
        ],
        "HEALTH PROFESSIONS"=>[
            "Chiropractic",
            "Dental Assisting",
            "Dental Hygiene",
            "Dental Lab Technology",
            "Dentistry",
            "Emergency Medical Tech.",
            "Medical/Surgical Assistant",
            "Medical Lab/Tech.",
            "Medicine",
            "Nuclear Medical Tech.",
            "Nursing",
            "Occupational Therapy",
            "Optometry",
            "Pharmacy",
            "Physician Assisting",
            "Physical Therapy",
            "Radiology",
            "Respiratory Therapy",
            "Speech Path./Audiology",
            "Veterinarian Assisting",
            "Veterinary Medicine",
            "Other Health Professions",
        ],
        "HOME ECONOMICS"=>[
            "Child Development",
            "Culinary Arts",
            "Family Resource Management",
            "Fashion Design",
            "Food/Nutrition/Dietetics",
            "Human Environment & Housing",
            "Individual & Family Development",
            "Textiles & Clothing",
            "Other Home Economics Majors",
        ],
        "LETTERS"=>[
            "Classics",
            "Comparative Literature",
            "Creative Writing",
            "English",
            "Linguistics",
            "Literature, English",
            "Speech/Debate,",
        ],
        "MATHEMATICS"=>[
            "Actuarial Sciences",
            "Applied Mathematics",
            "Statistics",
            "Other Mathematics",
        ],
        "PHILOSOPHY/RELIGION"=>[
            "PHILOSOPHY/RELIGION"
        ],
        "PHYSICAL SCIENCES"=>[
            "Astronomy",
            "Meteorology",
            "Chemistry",
            "Earth Science",
            "Geology",
            "Oceanography",
            "Physics",
            "Other Physical Sciences",
        ],
        "SOCIAL SCIENCES"=>[
            "Anthropology",
            "Economics",
            "Geography",
            "History",
            "International Relations",
            "Law",
            "Political Science",
            "Psychology",
            "Sociology",
            "Other Social Sciences",
        ],
        "TRADE & INDUSTRIAL"=>[
            "Aircraft Mechanics",
            "Automotive Repair",
            "Construction/Carpentry",
            "Diesel Mechanics",
            "Drafting",
            "Electronic Equipment/Repair",
            "Heating, Air Conditioning &",
            "Refrigeration Technology",
            "Instrument Maintenance & Repair",
            "Machinework",
            "Masonry",
            "Radio/TV Repair",
            "Welding",
            "Woodworking",
            "Other Trade & Industrial Majors",
        ]
    ],
    'counties'=>[
       "Afghanistan 	",
       "Åland Islands 	",
       "Albania 	",
       "Algeria 	",
       "American Samoa ",
       "Andorra 	",
       "Angola 	",
       "Anguilla 	",
       "Antarctica ",
       "Antigua and Barbuda 	",
       "Argentina 	",
       "Armenia 	",
       "Aruba ",
       "Australia ",
       "Austria ",
       "Azerbaijan ",
       "Bahamas 	",
       "Bahrain ",
       "Bangladesh",
       "Barbados ",
       "Belarus ",
       "Belgium ",
       "Belize 	",
       "Benin ",
       "Bermuda ",
       "Bhutan ",
       "Bolivia (Plurinational State of) ",
       "Bonaire, Sint Eustatius and Saba ",
       "Bosnia and Herzegovina ",
       "Botswana ",
       "Bouvet Island ",
       "Brazil ",
       "British Indian Ocean Territory ",
       "Brunei Darussalam 	",
       "Bulgaria 	",
       "Burkina Faso ",
       "Burundi ",
       "Cabo Verde ",
       "Cambodia ",
       "Cameroon ",
       "Canada ",
       "Cayman Islands ",
       "Central African Republic ",
       "Chad 	",
       "Chile ",
       "China ",
       "Christmas Island ",
       "Cocos (Keeling) Islands ",
       "Colombia 	",
       "Comoros 	",
       "Congo ",
       "Congo, Democratic Republic of the ",
       "Cook Islands 	",
       "Costa Rica ",
       "Côte d'Ivoire ",
       "Croatia 	",
       "Cuba 	",
       "Curaçao ",
       "Cyprus ",
       "Czechia ",
       "Denmark ",
       "Djibouti ",
       "Dominica 	",
       "Dominican Republic ",
       "Ecuador 	",
       "Egypt ",
       "El Salvador 	",
       "Equatorial Guinea ",
       "Eritrea 	",
       "Estonia 	",
       "Eswatini 	",
       "Ethiopia 	",
       "Falkland Islands (Malvinas) 	",
       "Faroe Islands 	",
       "Fiji 	",
       "Finland 	",
       "France ",
       "French Guiana ",
       "French Polynesia ",
       "French Southern Territories ",
       "Gabon 	",
       "Gambia ",
       "Georgia 	",
       "Germany 	",
       "Ghana ",
       "Gibraltar ",
       "Greece ",
       "Greenland 	",
       "Grenada 	",
       "Guadeloupe ",
       "Guam 	",
       "Guatemala ",
       "Guernsey 	",
       "Guinea ",
       "Guinea-Bissau ",
       "Guyana ",
       "Haiti 	",
       "Heard Island and McDonald Islands ",
       "Holy See 	",
       "Honduras 	",
       "Hong Kong ",
       "Hungary 	",
       "Iceland 	",
       "India 	",
       "Indonesia ",
       "Iran (Islamic Republic of) ",
       "Iraq 	",
       "Ireland 	",
       "Isle of Man 	",
       "Israel ",
       "Italy ",
       "Jamaica 	",
       "Japan 	",
       "Jersey ",
       "Jordan ",
       "Kazakhstan ",
       "Kenya 	",
       "Kiribati ",
       "Korea (Democratic People's Republic of) ",
       "Korea, Republic of 	KR ",
       "Kuwait ",
       "Kyrgyzstan ",
       "Lao People's Democratic Republic ",
       "Latvia 	",
       "Lebanon 	",
       "Lesotho ",
       "Liberia ",
       "Libya ",
       "Liechtenstein ",
       "Lithuania ",
       "Luxembourg 	",
       "Macao ",
       "Madagascar ",
       "Malawi ",
       "Malaysia ",
       "Maldives 	",
       "Mali 	",
       "Malta ",
       "Marshall Islands ",
       "Martinique ",
       "Mauritania ",
       "Mauritius ",
       "Mayotte 	",
       "Mexico ",
       "Micronesia (Federated States of) ",
       "Moldova, Republic of 	MD ",
       "Monaco ",
       "Mongolia 	",
       "Montenegro ",
       "Montserrat 	",
       "Morocco 	",
       "Mozambique ",
       "Myanmar 	",
       "Namibia ",
       "Nauru 	",
       "Nepal ",
       "Netherlands ",
       "New Caledonia ",
       "New Zealand 	",
       "Nicaragua 	",
       "Niger 	",
       "Nigeria ",
       "Niue 	",
       "Norfolk Island ",
       "North Macedonia ",
       "Northern Mariana Islands ",
       "Norway ",
       "Oman 	",
       "Pakistan ",
       "Palau ",
       "Palestine, State of ",
       "Panama 	",
       "Papua New Guinea ",
       "Paraguay ",
       "Peru ",
       "Philippines ",
       "Pitcairn ",
       "Poland ",
       "Portugal 	",
       "Puerto Rico ",
       "Qatar ",
       "Réunion ",
       "Romania ",
       "Russian Federation",
       "Rwanda 	RW 	RWA ",
       "Saint Barthélemy ",
       "Saint Helena, Ascension and Tristan da Cunha 	",
       "Saint Kitts and Nevis ",
       "Saint Lucia 	",
       "Saint Martin (French part) ",
       "Saint Pierre and Miquelon ",
       "Saint Vincent and the Grenadines ",
       "Samoa 	",
       "San Marino ",
       "Sao Tome and Principe ",
       "Saudi Arabia 	",
       "Senegal ",
       "Serbia ",
       "Seychelles ",
       "Sierra Leone ",
       "Singapore 	",
       "Sint Maarten (Dutch part) ",
       "Slovakia 	",
       "Slovenia 	",
       "Solomon Islands 	",
       "Somalia 	",
       "South Africa 	",
       "South Georgia and the South Sandwich Islands 	",
       "South Sudan ",
       "Spain 	",
       "Sri Lanka 	",
       "Sudan 	",
       "Suriname 	",
       "Svalbard and Jan Mayen ",
       "Sweden ",
       "Switzerland 	",
       "Syrian Arab Republic ",
       "Taiwan, Province of China ",
       "Tajikistan ",
       "Tanzania, United Republic of ",
       "Thailand ",
       "Timor-Leste 	",
       "Togo 	",
       "Tokelau ",
       "Tonga ",
       "Trinidad and Tobago ",
       "Tunisia 	",
       "Turkey 	",
       "Turkmenistan 	",
       "Turks and Caicos Islands 	",
       "Tuvalu 	",
       "Uganda ",
       "Ukraine ",
       "United Arab Emirates ",
       "United Kingdom of Great Britain and Northern Ireland 	",
       "United States of America ",
       "United States Minor Outlying Islands ",
       "Uruguay 	",
       "Uzbekistan ",
       "Vanuatu 	",
       "Venezuela (Bolivarian Republic of) ",
       "Viet Nam 	",
       "Virgin Islands (British) ",
       "Virgin Islands (U.S.) ",
       "Wallis and Futuna 	",
       "Western Sahara ",
       "Yemen ",
       "Zambia ",
       "Zimbabwe ",
    ]
];